// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockApp.Infrastructure.Persistence;

#nullable disable

namespace StockApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721153410_IdImportacionTrazabilidad")]
    partial class IdImportacionTrazabilidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockApp.Domain.Entities.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAltaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GastoId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PagoGastoId")
                        .HasColumnType("integer");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GastoId");

                    b.HasIndex("PagoGastoId");

                    b.ToTable("Adjuntos", t =>
                        {
                            t.HasCheckConstraint("CK_Adjuntos_GastoOPago", "(\"GastoId\" IS NOT NULL AND \"PagoGastoId\" IS NULL) OR (\"GastoId\" IS NULL AND \"PagoGastoId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("StockApp.Domain.Entities.AdjuntoContenido", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("AdjuntosContenido");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.AsignacionPresupuestal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FuenteFinanciamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("LineaPoaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("FuenteFinanciamientoId");

                    b.HasIndex("LineaPoaId", "FuenteFinanciamientoId")
                        .IsUnique();

                    b.ToTable("AsignacionesPresupuestales");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.FuenteFinanciamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("FuentesFinanciamiento");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CondicionPago")
                        .HasColumnType("integer");

                    b.Property<string>("Destino")
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FuenteFinanciamientoId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdImportacion")
                        .HasColumnType("uuid");

                    b.Property<int?>("LineaPoaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("text");

                    b.Property<string>("NumeroOrden")
                        .HasColumnType("text");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroGastoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("FuenteFinanciamientoId");

                    b.HasIndex("IdImportacion");

                    b.HasIndex("LineaPoaId");

                    b.HasIndex("RubroGastoId");

                    b.HasIndex("ProveedorId", "NumeroFactura")
                        .IsUnique()
                        .HasFilter("\"Activo\" = TRUE AND \"NumeroFactura\" IS NOT NULL");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.IngresoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FuenteFinanciamientoId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdImportacion")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("FuenteFinanciamientoId");

                    b.HasIndex("IdImportacion");

                    b.ToTable("IngresosCaja");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.LineaPoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdImportacion")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Programa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdImportacion");

                    b.HasIndex("Nombre", "Ejercicio")
                        .IsUnique();

                    b.ToTable("LineasPoa");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GastoId")
                        .HasColumnType("integer");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GastoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProductoId", "Fecha")
                        .HasDatabaseName("IX_MovimientosStock_ProductoId_Fecha");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.PagoGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GastoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Nota")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GastoId");

                    b.ToTable("PagosGasto");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasFilter("\"CodigoBarras\" IS NOT NULL");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.RubroGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("RubrosGasto");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Abreviatura")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Adjunto", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.Gasto", "Gasto")
                        .WithMany()
                        .HasForeignKey("GastoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockApp.Domain.Entities.PagoGasto", "PagoGasto")
                        .WithMany()
                        .HasForeignKey("PagoGastoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gasto");

                    b.Navigation("PagoGasto");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.AdjuntoContenido", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.Adjunto", null)
                        .WithOne()
                        .HasForeignKey("StockApp.Domain.Entities.AdjuntoContenido", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockApp.Domain.Entities.AsignacionPresupuestal", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.FuenteFinanciamiento", "FuenteFinanciamiento")
                        .WithMany()
                        .HasForeignKey("FuenteFinanciamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockApp.Domain.Entities.LineaPoa", null)
                        .WithMany("Asignaciones")
                        .HasForeignKey("LineaPoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FuenteFinanciamiento");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Gasto", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.FuenteFinanciamiento", "FuenteFinanciamiento")
                        .WithMany()
                        .HasForeignKey("FuenteFinanciamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockApp.Domain.Entities.LineaPoa", "LineaPoa")
                        .WithMany()
                        .HasForeignKey("LineaPoaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockApp.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockApp.Domain.Entities.RubroGasto", "RubroGasto")
                        .WithMany()
                        .HasForeignKey("RubroGastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FuenteFinanciamiento");

                    b.Navigation("LineaPoa");

                    b.Navigation("Proveedor");

                    b.Navigation("RubroGasto");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.IngresoCaja", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.FuenteFinanciamiento", "FuenteFinanciamiento")
                        .WithMany()
                        .HasForeignKey("FuenteFinanciamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FuenteFinanciamiento");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.MovimientoStock", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.Gasto", "Gasto")
                        .WithMany()
                        .HasForeignKey("GastoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockApp.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gasto");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.PagoGasto", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.Gasto", "Gasto")
                        .WithMany("Pagos")
                        .HasForeignKey("GastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gasto");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Producto", b =>
                {
                    b.HasOne("StockApp.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StockApp.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StockApp.Domain.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.Gasto", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("StockApp.Domain.Entities.LineaPoa", b =>
                {
                    b.Navigation("Asignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
